repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black .
        language: system
        types: [ python ]
        pass_filenames: false

      - id: tests
        name: tests
        entry: make test
        language: system
        pass_filenames: false