services:
  app:
    container_name: app-test
    build:
      context: ./
      dockerfile: ./api/Dockerfile
    command: "sh -c 'alembic revision --autogenerate && alembic upgrade head && uvicorn asgi:app --host 0.0.0.0 --port 8000 --reload'"
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      - backend-test
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    container_name: db-test
    image: mysql:latest
    restart: unless-stopped
    healthcheck:
      test: "mysql -u root -p${MYSQL_ROOT_PASSWORD} -e 'select 1;'"
      interval: 1s
      retries: 50
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
    networks:
      - backend-test
    env_file:
      - .env
    ports:
      - 5555:3306
  redis:
    container_name: redis-test
    image: redis:latest
    restart: unless-stopped
    healthcheck:
      test: "redis-cli ping"
      interval: 1s
      retries: 50
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
    networks:
      - backend-test
    env_file:
      - .env

networks:
  backend-test:
    driver: bridge
